openapi: '3.0.0'
info:
  version: 1.0.0
  title: MyCare API
  license:
    name: MIT
servers:
  - url: http://api.mycare.com/v1
paths:
  /vitals:
    get:
      summary: List all vitals
      operationId: listVitals
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: An paged array of vitals
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vitals'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create a vital
      operationId: createVital
      responses:
        201:
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /vitals/{vitalId}:
    get:
      summary: Vital details
      operationId: showVitalById
      parameters:
        - name: vitalId
          in: path
          required: true
          description: The id of the vital entry to retrieve
          schema:
            type: string
      responses:
        200:
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vitals'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /care-programs:
    get:
      summary: List care programs
      operationId: listCarePrograms
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: A paged array of care programs
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CarePrograms'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Enroll program
      operationId: enrollProgram
      responses:
        201:
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Vital:
      required:
        - id
        - type
      properties:
        id:
          type: integer
          format: int64
        type:
          type: string
        value:
          type: string
    Vitals:
      type: array
      items:
        $ref: '#/components/schemas/Vital'
    CareProgram:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
    CarePrograms:
      type: array
      items:
        $ref: '#/components/schemas/CareProgram'
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string